#!/bin/bash

# Get the Python file name from the environment variable
python_file="$PYFILE"

# Check if the file exists
if [ -f "$python_file" ]; then
  echo "Running $python_file"
  # Run the Python script
  python "$python_file"
else
  echo "Python file not found: $python_file"
fi
